/* tslint:disable */
/* eslint-disable */
/**
 * Lethean Binary API
 * Functionality to simplify using LTHN
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: contact@lethean.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface StartLetheandRequest {
    dataDir: string;
    version?: boolean;
}

/**
 * 
 */
export class VpnApi extends runtime.BaseAPI {

    /**
     */
    async startLetheandRaw(requestParameters: StartLetheandRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.dataDir === null || requestParameters.dataDir === undefined) {
            throw new runtime.RequiredError('dataDir','Required parameter requestParameters.dataDir was null or undefined when calling startLetheand.');
        }

        const queryParameters: any = {};

        if (requestParameters.version !== undefined) {
            queryParameters['version'] = requestParameters.version;
        }

        if (requestParameters.dataDir !== undefined) {
            queryParameters['data_dir'] = requestParameters.dataDir;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/letheand/start`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async startLetheand(requestParameters: StartLetheandRequest, initOverrides?: RequestInit): Promise<void> {
        await this.startLetheandRaw(requestParameters, initOverrides);
    }

}
